### ISSUE TITLE
--nomodule option doesn't work, module URL Parameter required.

### ISSUE THREAD

**Issue by HM-Marisa** [skuid/skuid-sfdx#15]
We have a number of pages that aren't in a module, and so to pull them, I tried to use `--nomodule` but that doesn't appear to be working, or I am missing something (a setting maybe?).

Hopefully you can help.

I ran `sfdx skuid:page:pull --nomodule --json` and here is the result:

```json
{
    "status": 1,
    "name": "TypeError",
    "message": "Cannot create property 'content' on string 'You must provide a \"module\" URL Parameter containing the name, or comma-separated names, of the Modules of pages you would like to retrieve'",
    "exitCode": 1,
    "commandName": "Pull",
    "stack": "TypeError: Cannot create property 'content' on string 'You must provide a \"module\" URL Parameter containing the name, or comma-separated names, of the Modules of pages you would like to retrieve'\n    at /Users/mclardy/.local/share/sfdx/node_modules/skuid-sfdx/lib/commands/skuid/page/pull.js:38:36\n    at Array.forEach (<anonymous>)\n    at Pull.run (/Users/mclardy/.local/share/sfdx/node_modules/skuid-sfdx/lib/commands/skuid/page/pull.js:35:33)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Pull._run (/Users/mclardy/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:91:40)\n    at async Config.runCommand (/Users/mclardy/.local/share/sfdx/client/7.82.0-3d0c527ac6/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/Users/mclardy/.local/share/sfdx/client/7.82.0-3d0c527ac6/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/Users/mclardy/.local/share/sfdx/client/7.82.0-3d0c527ac6/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/mclardy/.local/share/sfdx/client/7.82.0-3d0c527ac6/dist/cli.js:32:20)\nOuter stack:\n    at Function.wrap (/Users/mclardy/.local/share/sfdx/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at Pull.catch (/Users/mclardy/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:255:67)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Pull._run (/Users/mclardy/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:95:13)\n    at async Config.runCommand (/Users/mclardy/.local/share/sfdx/client/7.82.0-3d0c527ac6/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/Users/mclardy/.local/share/sfdx/client/7.82.0-3d0c527ac6/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/Users/mclardy/.local/share/sfdx/client/7.82.0-3d0c527ac6/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/mclardy/.local/share/sfdx/client/7.82.0-3d0c527ac6/dist/cli.js:32:20)",
    "warnings": []
}
```

The main issue is this here: You must provide a "module" URL Parameter containing the name, or comma-separated names, of the Modules of pages you would like to retrieve

This goes counter to pulling individual pages or no module altogether, does it not?

Trying to run `sfdx skuid:page:pull --module="" --json` produces the same result, so it doesn't appear that I can trick it into working either.

Any help would be appreciated, thanks.

**Comment by HM-Marisa** [comment]
Skuid version 11.2.8

**Comment by blardo** [comment]
I believe this issue arises from an outdated Skuid version. The `--nomodule` functionality was added in `11.2.12`. An upgrade should allow this to work as expected.

**Comment by HM-Marisa** [comment]
Hmmm, ok. That is good to know. Why is `--nomodule` listed in the [11.2.8](https://docs.skuid.com/v11.2.8/en/skuid/skuid-sfdx/) version of your docs then? 
Additionally, even on your latest version of the [XML API](https://docs.skuid.com/v13.0.10/v2/en/skuid/api/page-xml/#api-reference) docs doesn't list nomodule as an option, so that is why I was very confused.

I've relayed the need to update to my superiors, but I think we'll just need to work around it by adding them to a module in the meantime.

Thank you for the answer.
