### ISSUE TITLE
Failed to write to file if module name contains '/'

### ISSUE THREAD

**Issue by jmcdo29** [skuid/skuid-sfdx#6]
In the Salesforce Org I am working in, if the module name contains the string `/`, then an error appears about not being able to write to file `<projectRoot>/skuidpages/<moduleNameBeforeSlash>/<moduleNameAfterSlash>_pageName.xml`. Pretty obvious what the error is, and I'd be happy to raise a PR to fix this, as I've got a patch working locally. Let me know what you think.

For the patch, I'm thinking of replacing the `/` with a `-`, that way it does not collide with the naming convention of `module_pageName`, but still allows for the use of modules with a forward slash in their name. Thoughts?

**Comment by zachelrath** [comment]
Hey Jay, thanks for reporting this, makes sense. I think replacing with a `-` is a reasonable fix, a patch would be great!
